version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: laravel-app
    user: laravel
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "8000:80"
    command: 
      - /bin/bash
      - -c 
      - |
        php artisan migrate --seed --no-interaction --force
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - mysql-db
    networks:
      - laravel-net

  # NextJS Application
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    container_name: nextjs-app
    volumes:
      - ./nextjs:/app
      - /app/node_modules # Ignore node_modules directory
    ports:
      - "3000:3000"
    networks:
      - laravel-net

  # MySQL Database
  mysql-db:
    image: mysql:8
    container_name: laravel-mysql
    ports:
      - "3306:3306"
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      # MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: laravel_react
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      # MYSQL_USER: root
      # MYSQL_PASSWORD:
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - laravel-net

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-db
      # PMA_ARBITRARY: 1
      # MYSQL_ROOT_PASSWORD:
    networks:
      - laravel-net

networks:
  laravel-net: